/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sketchide;

import javax.swing.SwingUtilities;
import org.sketchide.ui.SketchIDEFrame;

public class Main {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(SketchIDEFrame::new);
    }
}
