/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sketchide;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
